language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls 
  
# command to run tests 
script: 
  - nose2 -v --with-coverage --coverage app

after_success: - coveralls